name: Webapp CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  webapp-build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install Dependencies
        working-directory: webapp
        run: npm install

      - name: Lint
        working-directory: webapp
        run: npm run lint

      - name: Run Tests
        working-directory: webapp
        run: npm run test
